import { TerraformingMarsCard } from "./types";

/**
 * Terraforming Mars card database
 * Expansions: Base Game, Prelude, Colonies
 *
 * IMPORTANT NOTES on the "tr" field:
 * - tr represents EXTRA TR that is NOT from global parameter changes
 * - Temperature steps, oxygen steps, and ocean placements already give +1 TR each
 *   (this is calculated in the valuation engine via calcGlobalParameterValue)
 * - Only use tr for ADDITIONAL TR beyond what global params give
 *   (e.g., Nitrogen-Rich Asteroid: "Raise your TR 2 steps. Raise temperature 1 step.")
 *
 * Card data sourced from official rules, ssimeonoff.github.io, and the open source game
 */

export const ALL_CARDS: TerraformingMarsCard[] = [
  // ========================================
  // BASE GAME PROJECT CARDS (208 cards)
  // ========================================

  // --- Automated cards ---
  { id: 1, name: "Colonizer Training Camp", cost: 8, type: "automated", tags: ["building", "jovian"], expansion: "base", requirements: { maxOxygen: 5 }, effects: { vp: 2 }, cardNumber: "001" },
  { id: 2, name: "Asteroid Mining Consortium", cost: 13, type: "automated", tags: ["jovian"], expansion: "base", requirements: { minProduction: { titanium: 1 } }, effects: { production: { titanium: 1 }, vp: 1 }, cardNumber: "002" },
  { id: 3, name: "Deep Well Heating", cost: 13, type: "automated", tags: ["power", "building"], expansion: "base", effects: { production: { energy: 1 }, temperatureSteps: 1 }, cardNumber: "003" },
  { id: 4, name: "Cloud Seeding", cost: 11, type: "automated", tags: [], expansion: "base", requirements: { minOceans: 3 }, effects: { production: { megacredits: -1, plants: 2 } }, cardNumber: "004" },
  { id: 8, name: "Capital", cost: 26, type: "automated", tags: ["city", "building"], expansion: "base", requirements: { minOceans: 4 }, effects: { production: { energy: -2, megacredits: 5 }, cityTiles: 1, description: "1VP per adjacent ocean tile" }, cardNumber: "008" },
  { id: 16, name: "Domed Crater", cost: 24, type: "automated", tags: ["city", "building"], expansion: "base", requirements: { maxOxygen: 7 }, effects: { production: { energy: -1, megacredits: 3 }, cityTiles: 1, resources: { plants: 3 } }, cardNumber: "016" },
  { id: 17, name: "Noctis City", cost: 18, type: "automated", tags: ["city", "building"], expansion: "base", effects: { production: { energy: -1, megacredits: 3 }, cityTiles: 1 }, cardNumber: "017" },
  { id: 18, name: "Methane From Titan", cost: 28, type: "automated", tags: ["space", "jovian"], expansion: "base", requirements: { minOxygen: 2 }, effects: { production: { heat: 2, plants: 2 }, vp: 2 }, cardNumber: "018" },
  { id: 21, name: "Phobos Space Haven", cost: 25, type: "automated", tags: ["space", "city"], expansion: "base", effects: { production: { titanium: 1 }, cityTiles: 1, vp: 3 }, cardNumber: "021" },
  { id: 22, name: "Black Polar Dust", cost: 15, type: "automated", tags: [], expansion: "base", effects: { production: { megacredits: -2, heat: 3 }, oceanTiles: 1 }, cardNumber: "022" },
  { id: 26, name: "Eos Chasma National Park", cost: 16, type: "automated", tags: ["plant", "building"], expansion: "base", requirements: { minTemperature: -12 }, effects: { production: { megacredits: 2 }, resources: { plants: 3 }, vp: 1, description: "Add 1 animal to any card." }, cardNumber: "026" },
  { id: 29, name: "Cupola City", cost: 16, type: "automated", tags: ["city", "building"], expansion: "base", requirements: { maxOxygen: 9 }, effects: { production: { energy: -1, megacredits: 3 }, cityTiles: 1 }, cardNumber: "029" },
  { id: 30, name: "Lunar Beam", cost: 13, type: "automated", tags: ["power", "earth"], expansion: "base", effects: { production: { megacredits: -2, heat: 2, energy: 2 } }, cardNumber: "030" },
  { id: 32, name: "Underground City", cost: 18, type: "automated", tags: ["city", "building"], expansion: "base", effects: { production: { energy: -2, steel: 2 }, cityTiles: 1 }, cardNumber: "032" },
  { id: 40, name: "Asteroid Mining", cost: 30, type: "automated", tags: ["space", "jovian"], expansion: "base", effects: { production: { titanium: 2 }, vp: 2 }, cardNumber: "040" },
  { id: 41, name: "Food Factory", cost: 12, type: "automated", tags: ["building"], expansion: "base", effects: { production: { plants: -1, megacredits: 4 }, vp: 1 }, cardNumber: "041" },
  { id: 42, name: "Archaebacteria", cost: 6, type: "automated", tags: ["microbe"], expansion: "base", requirements: { maxTemperature: -18 }, effects: { production: { plants: 1 } }, cardNumber: "042" },
  { id: 43, name: "Carbonate Processing", cost: 6, type: "automated", tags: ["building"], expansion: "base", effects: { production: { energy: -1, heat: 3 } }, cardNumber: "043" },
  { id: 44, name: "Natural Preserve", cost: 9, type: "automated", tags: ["science", "building"], expansion: "base", requirements: { maxOxygen: 4 }, effects: { production: { megacredits: 1 }, vp: 1 }, cardNumber: "044" },
  { id: 45, name: "Nuclear Power", cost: 10, type: "automated", tags: ["power", "building"], expansion: "base", effects: { production: { megacredits: -2, energy: 3 } }, cardNumber: "045" },
  { id: 46, name: "Lightning Harvest", cost: 8, type: "automated", tags: ["power"], expansion: "base", requirements: { tag: { tag: "science", count: 3 } }, effects: { production: { megacredits: 1, energy: 1 }, vp: 1 }, cardNumber: "046" },
  { id: 47, name: "Algae", cost: 10, type: "automated", tags: ["plant"], expansion: "base", requirements: { minOceans: 5 }, effects: { resources: { plants: 1 }, production: { plants: 2 } }, cardNumber: "047" },
  { id: 48, name: "Adapted Lichen", cost: 9, type: "automated", tags: ["plant"], expansion: "base", effects: { production: { plants: 1 } }, cardNumber: "048" },
  { id: 51, name: "Miranda Resort", cost: 12, type: "automated", tags: ["space", "jovian"], expansion: "base", effects: { production: { megacredits: 1 }, vp: 1, description: "+1MC prod per earth tag you have." }, cardNumber: "051" },
  { id: 53, name: "Lake Marineris", cost: 18, type: "automated", tags: [], expansion: "base", requirements: { minTemperature: 0 }, effects: { oceanTiles: 2, vp: 2 }, cardNumber: "053" },
  { id: 55, name: "Kelp Farming", cost: 17, type: "automated", tags: ["plant"], expansion: "base", requirements: { minOceans: 6 }, effects: { production: { megacredits: 2, plants: 3 }, resources: { plants: 2 }, vp: 1 }, cardNumber: "055" },
  { id: 56, name: "Mine", cost: 4, type: "automated", tags: ["building"], expansion: "base", effects: { production: { steel: 1 } }, cardNumber: "056" },
  { id: 57, name: "Vesta Shipyard", cost: 15, type: "automated", tags: ["space", "jovian"], expansion: "base", effects: { production: { titanium: 1 }, vp: 1 }, cardNumber: "057" },
  { id: 58, name: "Beam From A Thorium Asteroid", cost: 32, type: "automated", tags: ["space", "power", "jovian"], expansion: "base", requirements: { tag: { tag: "jovian", count: 1 } }, effects: { production: { heat: 3, energy: 3 }, vp: 1 }, cardNumber: "058" },
  { id: 59, name: "Mangrove", cost: 12, type: "automated", tags: ["plant"], expansion: "base", requirements: { minTemperature: 4 }, effects: { greeneryTiles: 1, vp: 1 }, cardNumber: "059" },
  { id: 60, name: "Trees", cost: 13, type: "automated", tags: ["plant"], expansion: "base", requirements: { minTemperature: -4 }, effects: { production: { plants: 3 }, resources: { plants: 1 }, vp: 1 }, cardNumber: "060" },
  { id: 61, name: "Great Escarpment Consortium", cost: 6, type: "automated", tags: [], expansion: "base", requirements: { minProduction: { steel: 1 } }, effects: { production: { steel: 1 } }, cardNumber: "061" },
  { id: 65, name: "Building Industries", cost: 6, type: "automated", tags: ["building"], expansion: "base", effects: { production: { energy: -1, steel: 2 } }, cardNumber: "065" },
  { id: 68, name: "Sponsors", cost: 6, type: "automated", tags: ["earth"], expansion: "base", effects: { production: { megacredits: 2 } }, cardNumber: "068" },
  { id: 80, name: "Immigration Shuttles", cost: 31, type: "automated", tags: ["space", "earth"], expansion: "base", effects: { production: { megacredits: 5 }, description: "1VP per 3 city tiles in play." }, cardNumber: "080" },
  { id: 82, name: "Immigrant City", cost: 13, type: "automated", tags: ["city", "building"], expansion: "base", effects: { production: { energy: -1, megacredits: -2 }, cityTiles: 1, description: "Effect: When a city is placed, +1MC prod." }, cardNumber: "082" },
  { id: 83, name: "Solar Power", cost: 11, type: "automated", tags: ["power", "building"], expansion: "base", effects: { production: { energy: 1 }, vp: 1 }, cardNumber: "083" },
  { id: 84, name: "Breathing Filters", cost: 11, type: "automated", tags: ["science"], expansion: "base", requirements: { minOxygen: 7 }, effects: { vp: 2 }, cardNumber: "084" },
  { id: 85, name: "Artificial Photosynthesis", cost: 12, type: "automated", tags: ["science"], expansion: "base", effects: { production: { energy: 2 }, description: "OR: +1 plant prod instead" }, cardNumber: "085" },
  { id: 86, name: "Artificial Lake", cost: 15, type: "automated", tags: [], expansion: "base", requirements: { minTemperature: -6 }, effects: { oceanTiles: 1, vp: 1 }, cardNumber: "086" },
  { id: 87, name: "Geothermal Power", cost: 11, type: "automated", tags: ["power", "building"], expansion: "base", effects: { production: { energy: 2 } }, cardNumber: "087" },
  { id: 88, name: "Farming", cost: 16, type: "automated", tags: ["plant"], expansion: "base", requirements: { minTemperature: 4 }, effects: { production: { megacredits: 2, plants: 2 }, resources: { plants: 2 }, vp: 2 }, cardNumber: "088" },
  { id: 89, name: "Dust Seals", cost: 2, type: "automated", tags: [], expansion: "base", requirements: { maxOceans: 3 }, effects: { vp: 1 }, cardNumber: "089" },
  { id: 90, name: "Urbanized Area", cost: 10, type: "automated", tags: ["city", "building"], expansion: "base", effects: { production: { energy: -1, megacredits: 2 }, cityTiles: 1 }, cardNumber: "090" },
  { id: 92, name: "Moss", cost: 4, type: "automated", tags: ["plant"], expansion: "base", requirements: { minOceans: 3 }, effects: { production: { plants: 1 }, description: "Lose 1 plant." }, cardNumber: "092" },
  { id: 95, name: "Hackers", cost: 3, type: "automated", tags: [], expansion: "base", effects: { production: { energy: -1, megacredits: 2 } }, cardNumber: "095" },
  { id: 96, name: "GHG Factories", cost: 11, type: "automated", tags: ["building"], expansion: "base", effects: { production: { energy: -1, heat: 4 } }, cardNumber: "096" },
  { id: 97, name: "Plantation", cost: 15, type: "automated", tags: ["plant"], expansion: "base", requirements: { tag: { tag: "science", count: 2 } }, effects: { greeneryTiles: 1 }, cardNumber: "097" },
  { id: 98, name: "Power Plant", cost: 4, type: "automated", tags: ["power", "building"], expansion: "base", effects: { production: { energy: 1 } }, cardNumber: "141" },
  { id: 99, name: "Mohole Area", cost: 20, type: "automated", tags: ["building"], expansion: "base", effects: { production: { heat: 4 } }, cardNumber: "142" },
  { id: 101, name: "Titanium Mine", cost: 7, type: "automated", tags: ["building"], expansion: "base", effects: { production: { titanium: 1 } }, cardNumber: "144" },
  { id: 102, name: "Strip Mine", cost: 25, type: "automated", tags: ["building"], expansion: "base", effects: { production: { energy: -2, steel: 2, titanium: 1 }, oxygenSteps: 2 }, cardNumber: "145" },
  { id: 103, name: "Wave Power", cost: 8, type: "automated", tags: ["power"], expansion: "base", requirements: { minOceans: 5 }, effects: { production: { energy: 1 }, vp: 1 }, cardNumber: "139" },
  { id: 105, name: "Power Grid", cost: 18, type: "automated", tags: ["power"], expansion: "base", effects: { production: { energy: 1 }, description: "+1 energy prod per power tag." }, cardNumber: "102" },
  { id: 109, name: "Acquired Company", cost: 10, type: "automated", tags: ["earth"], expansion: "base", effects: { production: { megacredits: 3 } }, cardNumber: "106" },
  { id: 110, name: "Media Archives", cost: 8, type: "automated", tags: ["earth"], expansion: "base", effects: { description: "Gain 1MC for each event ever played." }, cardNumber: "107" },
  { id: 116, name: "Bushes", cost: 10, type: "automated", tags: ["plant"], expansion: "base", requirements: { minTemperature: -10 }, effects: { production: { plants: 2 }, resources: { plants: 2 } }, cardNumber: "093" },
  { id: 120, name: "Nuclear Zone", cost: 10, type: "automated", tags: [], expansion: "base", effects: { temperatureSteps: 2, vp: -2 }, cardNumber: "097" },
  { id: 121, name: "Tropical Resort", cost: 13, type: "automated", tags: ["building"], expansion: "base", effects: { production: { heat: -2, megacredits: 3 }, vp: 2 }, cardNumber: "098" },
  { id: 122, name: "Toll Station", cost: 12, type: "automated", tags: ["space"], expansion: "base", effects: { production: { megacredits: 1 }, description: "+1MC prod per space tag opponents have." }, cardNumber: "099" },
  { id: 123, name: "Fueled Generators", cost: 1, type: "automated", tags: ["power", "building"], expansion: "base", effects: { production: { megacredits: -1, energy: 1 } }, cardNumber: "100" },
  { id: 125, name: "Power Supply Consortium", cost: 5, type: "automated", tags: ["power"], expansion: "base", requirements: { tag: { tag: "power", count: 2 } }, effects: { production: { energy: 1 } }, cardNumber: "160" },
  { id: 129, name: "Micro-Mills", cost: 3, type: "automated", tags: [], expansion: "base", effects: { production: { heat: 1 } }, cardNumber: "164" },
  { id: 130, name: "Magnetic Field Generators", cost: 20, type: "automated", tags: ["building"], expansion: "base", effects: { production: { energy: -4, plants: 2 }, tr: 3 }, cardNumber: "165" },
  { id: 133, name: "Windmills", cost: 6, type: "automated", tags: ["power", "building"], expansion: "base", requirements: { minOxygen: 7 }, effects: { production: { energy: 1 }, vp: 1 }, cardNumber: "168" },
  { id: 134, name: "Zeppelins", cost: 13, type: "automated", tags: [], expansion: "base", requirements: { minOxygen: 5 }, effects: { production: { megacredits: 1 }, vp: 1, description: "+1MC prod per city you have." }, cardNumber: "169" },
  { id: 135, name: "Worms", cost: 8, type: "automated", tags: ["microbe"], expansion: "base", requirements: { minOxygen: 4 }, effects: { production: { plants: 2 } }, cardNumber: "170" },
  { id: 137, name: "Fusion Power", cost: 14, type: "automated", tags: ["science", "power", "building"], expansion: "base", requirements: { tag: { tag: "power", count: 2 } }, effects: { production: { energy: 3 } }, cardNumber: "132" },
  { id: 140, name: "Advanced Ecosystems", cost: 11, type: "automated", tags: ["plant", "microbe", "animal"], expansion: "base", requirements: { tag: { tag: "plant", count: 1 } }, effects: { vp: 3 }, cardNumber: "135" },
  { id: 141, name: "Great Dam", cost: 12, type: "automated", tags: ["power", "building"], expansion: "base", requirements: { minOceans: 4 }, effects: { production: { energy: 2 }, vp: 1 }, cardNumber: "136" },
  { id: 142, name: "Cartel", cost: 8, type: "automated", tags: ["earth"], expansion: "base", effects: { production: { megacredits: 1 }, description: "+1MC prod per earth tag." }, cardNumber: "137" },
  { id: 147, name: "Nitrophilic Moss", cost: 8, type: "automated", tags: ["plant"], expansion: "base", requirements: { minOceans: 3 }, effects: { production: { plants: 2 }, description: "Lose 2 plants." }, cardNumber: "146" },
  { id: 149, name: "Insects", cost: 9, type: "automated", tags: ["microbe"], expansion: "base", requirements: { minOxygen: 6 }, effects: { production: { plants: 1 }, description: "+1 plant prod per plant tag." }, cardNumber: "148" },
  { id: 153, name: "Insulation", cost: 2, type: "automated", tags: [], expansion: "base", effects: { description: "Decrease heat prod any steps, increase MC prod same amount." }, cardNumber: "152" },
  { id: 156, name: "Designed Microorganisms", cost: 16, type: "automated", tags: ["science", "microbe"], expansion: "base", requirements: { maxTemperature: -14 }, effects: { production: { plants: 2 } }, cardNumber: "155" },
  { id: 159, name: "Industrial Microbes", cost: 12, type: "automated", tags: ["microbe", "building"], expansion: "base", effects: { production: { energy: 1, steel: 1 } }, cardNumber: "158" },
  { id: 160, name: "Lichen", cost: 7, type: "automated", tags: ["plant"], expansion: "base", requirements: { minTemperature: -24 }, effects: { production: { plants: 1 } }, cardNumber: "159" },
  { id: 162, name: "Open City", cost: 23, type: "automated", tags: ["city", "building"], expansion: "base", requirements: { minOxygen: 12 }, effects: { production: { energy: -1, megacredits: 4 }, cityTiles: 1, resources: { plants: 2 }, vp: 1 }, cardNumber: "108" },
  { id: 164, name: "Giant Space Mirror", cost: 17, type: "automated", tags: ["power", "space"], expansion: "base", effects: { production: { energy: 3 } }, cardNumber: "083a" },
  { id: 165, name: "Trans-Neptune Probe", cost: 6, type: "automated", tags: ["science", "space"], expansion: "base", effects: { vp: 1 }, cardNumber: "084" },
  { id: 166, name: "Commercial District", cost: 16, type: "automated", tags: ["building"], expansion: "base", effects: { production: { energy: -1, megacredits: 4 }, description: "Place tile. 1VP per adjacent city." }, cardNumber: "085" },
  { id: 167, name: "Robotic Workforce", cost: 9, type: "automated", tags: ["science"], expansion: "base", effects: { description: "Duplicate the production of one building tag card." }, cardNumber: "086" },
  { id: 168, name: "Grass", cost: 11, type: "automated", tags: ["plant"], expansion: "base", requirements: { minTemperature: -16 }, effects: { production: { plants: 1 }, resources: { plants: 3 } }, cardNumber: "087" },
  { id: 169, name: "Heater", cost: 3, type: "automated", tags: ["power", "building"], expansion: "base", effects: { production: { energy: -1, heat: 1 }, temperatureSteps: 1 }, cardNumber: "088" },
  { id: 170, name: "Peroxide Power", cost: 7, type: "automated", tags: ["power", "building"], expansion: "base", effects: { production: { megacredits: -1, energy: 2 } }, cardNumber: "089" },
  { id: 171, name: "Tropical Island", cost: 12, type: "automated", tags: ["plant", "building"], expansion: "base", requirements: { minOceans: 5 }, effects: { production: { plants: 1, megacredits: 2 }, vp: 1 }, cardNumber: "090a" },
  { id: 172, name: "Research", cost: 11, type: "automated", tags: ["science", "science"], expansion: "base", effects: { drawCards: 2, vp: 1 }, cardNumber: "090b" },
  { id: 173, name: "Gene Repair", cost: 12, type: "automated", tags: ["science"], expansion: "base", requirements: { tag: { tag: "science", count: 3 } }, effects: { production: { megacredits: 2 }, vp: 2 }, cardNumber: "091" },
  { id: 174, name: "Io Mining Industries", cost: 41, type: "automated", tags: ["space", "jovian"], expansion: "base", effects: { production: { titanium: 2, megacredits: 2 }, description: "1VP per jovian tag." }, cardNumber: "092" },
  { id: 177, name: "Satellites", cost: 10, type: "automated", tags: ["space"], expansion: "base", effects: { production: { megacredits: 1 }, description: "+1MC prod per space tag." }, cardNumber: "175" },
  { id: 178, name: "Noctis Farming", cost: 10, type: "automated", tags: ["plant", "building"], expansion: "base", requirements: { minTemperature: -20 }, effects: { production: { megacredits: 1 }, resources: { plants: 2 }, vp: 1 }, cardNumber: "176" },
  { id: 180, name: "Heat Trappers", cost: 6, type: "automated", tags: ["power", "building"], expansion: "base", effects: { production: { energy: 1 }, description: "Decrease any heat prod 2 steps." }, cardNumber: "178" },
  { id: 181, name: "Soil Factory", cost: 9, type: "automated", tags: ["building"], expansion: "base", effects: { production: { energy: -1, plants: 1 }, vp: 1 }, cardNumber: "179" },
  { id: 182, name: "Fuel Factory", cost: 6, type: "automated", tags: ["building"], expansion: "base", effects: { production: { energy: -1, megacredits: 1, titanium: 1 } }, cardNumber: "180" },
  { id: 186, name: "Ganymede Colony", cost: 20, type: "automated", tags: ["space", "jovian", "city"], expansion: "base", effects: { cityTiles: 1, description: "1VP per jovian tag." }, cardNumber: "081a" },
  { id: 187, name: "Callisto Penal Mines", cost: 24, type: "automated", tags: ["space", "jovian"], expansion: "base", effects: { production: { megacredits: 3 }, vp: 2 }, cardNumber: "082a" },
  { id: 189, name: "Soletta", cost: 35, type: "automated", tags: ["space"], expansion: "base", effects: { production: { heat: 7 } }, cardNumber: "203" },
  { id: 191, name: "Rad-Chem Factory", cost: 8, type: "automated", tags: ["building"], expansion: "base", effects: { production: { energy: -1 }, tr: 2 }, cardNumber: "205" },
  { id: 193, name: "Medical Lab", cost: 13, type: "automated", tags: ["science", "building"], expansion: "base", effects: { production: { megacredits: 1 }, vp: 1, description: "+1MC prod per building tag." }, cardNumber: "207" },
  { id: 196, name: "Rad-Suits", cost: 6, type: "automated", tags: [], expansion: "base", requirements: { minOceans: 2 }, effects: { production: { megacredits: 1 }, vp: 1 }, cardNumber: "186" },
  { id: 199, name: "Protected Valley", cost: 23, type: "automated", tags: ["plant", "building"], expansion: "base", effects: { production: { megacredits: 2 }, greeneryTiles: 1 }, cardNumber: "174" },
  { id: 200, name: "Magnetic Field Dome", cost: 5, type: "automated", tags: ["building"], expansion: "base", effects: { production: { energy: -2, plants: 1 }, tr: 1 }, cardNumber: "171a" },
  { id: 206, name: "Biomass Combustors", cost: 4, type: "automated", tags: ["power", "building"], expansion: "base", requirements: { minOxygen: 6 }, effects: { production: { energy: 2 }, description: "Decrease any plant prod 1." }, cardNumber: "183" },

  // --- Active cards ---
  { id: 5, name: "Search For Life", cost: 3, type: "active", tags: ["science"], expansion: "base", requirements: { maxOxygen: 6 }, effects: { vp: 3, description: "Action: Spend 1MC, reveal top card. If microbe tag, add science resource." }, cardNumber: "005" },
  { id: 6, name: "Inventors' Guild", cost: 9, type: "active", tags: ["science"], expansion: "base", effects: { description: "Action: Look at top card, buy or discard." }, cardNumber: "006" },
  { id: 7, name: "Martian Rails", cost: 13, type: "active", tags: ["building"], expansion: "base", effects: { description: "Action: Spend 1 energy to gain 1MC per city on Mars." }, cardNumber: "007" },
  { id: 12, name: "Water Import From Europa", cost: 25, type: "active", tags: ["space", "jovian"], expansion: "base", effects: { description: "Action: Pay 12MC to place an ocean tile. 1VP per jovian tag." }, cardNumber: "012" },
  { id: 13, name: "Space Elevator", cost: 27, type: "active", tags: ["space", "building"], expansion: "base", effects: { production: { titanium: 1 }, vp: 2, description: "Action: Spend 1 steel to gain 3MC." }, cardNumber: "013" },
  { id: 14, name: "Development Center", cost: 11, type: "active", tags: ["science", "building"], expansion: "base", effects: { description: "Action: Spend 1 energy to draw a card." }, cardNumber: "014" },
  { id: 15, name: "Equatorial Magnetizer", cost: 11, type: "active", tags: ["building"], expansion: "base", effects: { description: "Action: Decrease energy prod 1 to increase TR 1." }, cardNumber: "015" },
  { id: 20, name: "Research Outpost", cost: 18, type: "active", tags: ["science", "city", "building"], expansion: "base", effects: { cityTiles: 1, cardDiscount: 1 }, cardNumber: "020" },
  { id: 23, name: "Arctic Algae", cost: 12, type: "active", tags: ["plant"], expansion: "base", requirements: { maxTemperature: -12 }, effects: { resources: { plants: 1 }, description: "Effect: When anyone places an ocean, gain 2 plants." }, cardNumber: "023" },
  { id: 24, name: "Predators", cost: 14, type: "active", tags: ["animal"], expansion: "base", requirements: { minOxygen: 11 }, effects: { vpPerResource: { resource: "animal", per: 1 }, description: "Action: Remove 1 animal from any card, add here." }, cardNumber: "024" },
  { id: 25, name: "Space Station", cost: 10, type: "active", tags: ["space"], expansion: "base", effects: { vp: 1, description: "Effect: When you play a space tag, pay 2MC less." }, cardNumber: "025" },
  { id: 28, name: "Security Fleet", cost: 12, type: "active", tags: ["space"], expansion: "base", effects: { vpPerResource: { resource: "fighter", per: 1 }, description: "Action: Spend 1 titanium to add 1 fighter." }, cardNumber: "028" },
  { id: 31, name: "Optimal Aerobraking", cost: 7, type: "active", tags: ["space"], expansion: "base", effects: { description: "Effect: When you play a space event, gain 3MC and 3 heat." }, cardNumber: "031" },
  { id: 33, name: "Regolith Eaters", cost: 13, type: "active", tags: ["science", "microbe"], expansion: "base", effects: { description: "Action: Add 1 microbe, or remove 2 to raise oxygen 1." }, cardNumber: "033" },
  { id: 34, name: "GHG Producing Bacteria", cost: 8, type: "active", tags: ["science", "microbe"], expansion: "base", requirements: { minOxygen: 4 }, effects: { description: "Action: Add 1 microbe, or remove 2 to raise temp 1." }, cardNumber: "034" },
  { id: 35, name: "Ants", cost: 9, type: "active", tags: ["microbe"], expansion: "base", requirements: { minOxygen: 4 }, effects: { vpPerResource: { resource: "microbe", per: 2 }, description: "Action: Remove 1 microbe from any card, add here." }, cardNumber: "035" },
  { id: 38, name: "Rover Construction", cost: 8, type: "active", tags: ["building"], expansion: "base", effects: { description: "Effect: When any city is placed, gain 2MC." }, cardNumber: "038" },
  { id: 49, name: "Tardigrades", cost: 4, type: "active", tags: ["microbe"], expansion: "base", effects: { vpPerResource: { resource: "microbe", per: 4 }, description: "Action: Add 1 microbe here." }, cardNumber: "049" },
  { id: 52, name: "Fish", cost: 9, type: "active", tags: ["animal"], expansion: "base", requirements: { minTemperature: 2 }, effects: { production: { plants: -1 }, vpPerResource: { resource: "animal", per: 1 }, description: "Action: Add 1 animal here." }, cardNumber: "052" },
  { id: 54, name: "Small Animals", cost: 6, type: "active", tags: ["animal"], expansion: "base", requirements: { minOxygen: 6 }, effects: { production: { plants: -1 }, vpPerResource: { resource: "animal", per: 2 }, description: "Action: Add 1 animal here." }, cardNumber: "054" },
  { id: 69, name: "Electro Catapult", cost: 17, type: "active", tags: ["building"], expansion: "base", requirements: { maxOxygen: 8 }, effects: { production: { energy: -1 }, vp: 1, description: "Action: Spend 1 plant or 1 steel to gain 7MC." }, cardNumber: "069" },
  { id: 70, name: "Earth Catapult", cost: 23, type: "active", tags: ["earth"], expansion: "base", effects: { cardDiscount: 2, vp: 2 }, cardNumber: "070" },
  { id: 71, name: "Advanced Alloys", cost: 9, type: "active", tags: ["science"], expansion: "base", effects: { description: "Effect: Steel worth +1MC. Titanium worth +1MC." }, cardNumber: "071" },
  { id: 72, name: "Birds", cost: 10, type: "active", tags: ["animal"], expansion: "base", requirements: { minOxygen: 13 }, effects: { production: { plants: -2 }, vpPerResource: { resource: "animal", per: 1 }, description: "Action: Add 1 animal here." }, cardNumber: "072" },
  { id: 73, name: "Mars University", cost: 8, type: "active", tags: ["science", "building"], expansion: "base", effects: { description: "Effect: When you play a science tag, discard a card to draw a card." }, cardNumber: "073" },
  { id: 74, name: "Viral Enhancers", cost: 9, type: "active", tags: ["science", "microbe"], expansion: "base", effects: { description: "Effect: When you play animal/plant/microbe tag, add 1 resource or gain 1 plant." }, cardNumber: "074" },
  { id: 76, name: "Space Mirrors", cost: 3, type: "active", tags: ["power", "space"], expansion: "base", effects: { description: "Action: Spend 7MC to increase energy prod 1." }, cardNumber: "076" },
  { id: 81, name: "Restricted Area", cost: 11, type: "active", tags: ["science"], expansion: "base", effects: { description: "Action: Spend 2MC to draw a card." }, cardNumber: "081" },
  { id: 93, name: "Industrial Center", cost: 4, type: "active", tags: ["building"], expansion: "base", effects: { description: "Action: Spend 7MC to increase steel prod 1. Must be next to city." }, cardNumber: "093" },
  { id: 106, name: "Steelworks", cost: 15, type: "active", tags: ["building"], expansion: "base", effects: { description: "Action: Spend 4 energy to gain 2 steel and raise oxygen 1." }, cardNumber: "103" },
  { id: 107, name: "Ore Processor", cost: 13, type: "active", tags: ["building"], expansion: "base", effects: { description: "Action: Spend 4 energy to gain 1 titanium and raise oxygen 1." }, cardNumber: "104" },
  { id: 108, name: "Earth Office", cost: 1, type: "active", tags: ["earth"], expansion: "base", effects: { description: "Effect: Earth tags cost 3MC less." }, cardNumber: "105" },
  { id: 111, name: "Media Group", cost: 6, type: "active", tags: ["earth"], expansion: "base", effects: { description: "Effect: After you play an event, gain 3MC." }, cardNumber: "109" },
  { id: 112, name: "Business Network", cost: 4, type: "active", tags: ["earth"], expansion: "base", effects: { production: { megacredits: -1 }, description: "Action: Look at top card, buy or discard." }, cardNumber: "110" },
  { id: 118, name: "Physics Complex", cost: 12, type: "active", tags: ["science", "building"], expansion: "base", effects: { description: "Action: Spend 6 energy to add 1 science resource. 2VP per science resource." }, cardNumber: "095" },
  { id: 124, name: "Ironworks", cost: 11, type: "active", tags: ["building"], expansion: "base", effects: { description: "Action: Spend 4 energy to gain 1 steel and raise oxygen 1." }, cardNumber: "101" },
  { id: 131, name: "Shuttles", cost: 10, type: "active", tags: ["space"], expansion: "base", requirements: { minOxygen: 5 }, effects: { production: { energy: -1, megacredits: 2 }, vp: 1, description: "Effect: Space tags cost 2MC less." }, cardNumber: "166" },
  { id: 136, name: "Decomposers", cost: 5, type: "active", tags: ["microbe"], expansion: "base", requirements: { minOxygen: 3 }, effects: { vpPerResource: { resource: "microbe", per: 3 }, description: "Effect: When you play animal/plant/microbe tag, add 1 microbe." }, cardNumber: "131" },
  { id: 138, name: "Symbiotic Fungus", cost: 4, type: "active", tags: ["microbe"], expansion: "base", requirements: { minTemperature: -14 }, effects: { description: "Action: Add 1 microbe to any card." }, cardNumber: "133" },
  { id: 139, name: "Extreme-Cold Fungus", cost: 13, type: "active", tags: ["microbe"], expansion: "base", requirements: { maxTemperature: -10 }, effects: { description: "Action: Gain 1 plant or add 2 microbes to any card." }, cardNumber: "134" },
  { id: 144, name: "Pets", cost: 10, type: "active", tags: ["animal", "earth"], expansion: "base", effects: { resources: { plants: 1 }, vpPerResource: { resource: "animal", per: 2 }, description: "Effect: When any city is placed, add 1 animal. Cannot be removed." }, cardNumber: "172" },
  { id: 145, name: "Protected Habitats", cost: 5, type: "active", tags: [], expansion: "base", effects: { description: "Effect: Opponents cannot remove your plants/animals/microbes." }, cardNumber: "173" },
  { id: 148, name: "Herbivores", cost: 12, type: "active", tags: ["animal"], expansion: "base", requirements: { minOxygen: 8 }, effects: { production: { plants: -1 }, vpPerResource: { resource: "animal", per: 2 }, description: "Effect: When greenery placed, add 1 animal." }, cardNumber: "147" },
  { id: 151, name: "Anti-Gravity Technology", cost: 14, type: "active", tags: ["science"], expansion: "base", requirements: { tag: { tag: "science", count: 7 } }, effects: { cardDiscount: 2, vp: 3 }, cardNumber: "150" },
  { id: 154, name: "Adaptation Technology", cost: 12, type: "active", tags: ["science"], expansion: "base", effects: { vp: 1, description: "Effect: Global requirements +/- 2 steps." }, cardNumber: "153" },
  { id: 155, name: "Caretaker Contract", cost: 3, type: "active", tags: [], expansion: "base", effects: { description: "Action: Spend 8 heat to increase TR 1." }, cardNumber: "154" },
  { id: 157, name: "Standard Technology", cost: 6, type: "active", tags: ["science"], expansion: "base", effects: { description: "Effect: After a standard project, gain 3MC." }, cardNumber: "156" },
  { id: 158, name: "Nitrite Reducing Bacteria", cost: 11, type: "active", tags: ["microbe"], expansion: "base", effects: { resources: { megacredits: 3 }, description: "Action: Add 1 microbe, or remove 3 to increase TR 1." }, cardNumber: "157" },
  { id: 161, name: "Power Infrastructure", cost: 4, type: "active", tags: ["power", "building"], expansion: "base", effects: { description: "Action: Spend any energy to gain equal MC." }, cardNumber: "194" },
  { id: 176, name: "Mass Converter", cost: 8, type: "active", tags: ["science", "power"], expansion: "base", requirements: { tag: { tag: "science", count: 5 } }, effects: { production: { energy: 6 }, description: "Effect: Space tags cost 2MC less." }, cardNumber: "171" },
  { id: 179, name: "Water Splitting Plant", cost: 12, type: "active", tags: ["building"], expansion: "base", requirements: { minOceans: 2 }, effects: { description: "Action: Spend 3 energy to raise oxygen 1." }, cardNumber: "177" },
  { id: 184, name: "Quantum Extractor", cost: 13, type: "active", tags: ["science", "power"], expansion: "base", requirements: { tag: { tag: "science", count: 4 } }, effects: { production: { energy: 4 }, description: "Effect: Space tags cost 2MC less." }, cardNumber: "079a" },
  { id: 194, name: "AI Central", cost: 21, type: "active", tags: ["science", "building"], expansion: "base", requirements: { tag: { tag: "science", count: 3 } }, effects: { production: { energy: -1 }, vp: 1, description: "Action: Draw 2 cards." }, cardNumber: "208" },
  { id: 197, name: "Penguins", cost: 7, type: "active", tags: ["animal"], expansion: "base", requirements: { minOceans: 8 }, effects: { vpPerResource: { resource: "animal", per: 1 }, description: "Action: Add 1 animal here." }, cardNumber: "212" },

  // --- Event cards ---
  { id: 9, name: "Asteroid", cost: 14, type: "event", tags: ["space"], expansion: "base", effects: { temperatureSteps: 1, resources: { titanium: 2 } }, cardNumber: "009" },
  { id: 10, name: "Comet", cost: 21, type: "event", tags: ["space"], expansion: "base", effects: { temperatureSteps: 1, oceanTiles: 1 }, cardNumber: "010" },
  { id: 11, name: "Big Asteroid", cost: 27, type: "event", tags: ["space"], expansion: "base", effects: { temperatureSteps: 2, resources: { titanium: 4 } }, cardNumber: "011" },
  { id: 19, name: "Imported Hydrogen", cost: 16, type: "event", tags: ["space", "earth"], expansion: "base", effects: { oceanTiles: 1, resources: { plants: 3 } }, cardNumber: "019" },
  { id: 27, name: "Interstellar Colony Ship", cost: 24, type: "event", tags: ["space", "earth"], expansion: "base", requirements: { tag: { tag: "science", count: 5 } }, effects: { vp: 4 }, cardNumber: "027" },
  { id: 36, name: "Release of Inert Gases", cost: 14, type: "event", tags: [], expansion: "base", effects: { tr: 2 }, cardNumber: "036" },
  { id: 37, name: "Nitrogen-Rich Asteroid", cost: 31, type: "event", tags: ["space"], expansion: "base", effects: { tr: 2, temperatureSteps: 1, resources: { plants: 4 } }, cardNumber: "037" },
  { id: 39, name: "Deimos Down", cost: 31, type: "event", tags: ["space"], expansion: "base", effects: { temperatureSteps: 3, resources: { steel: 4 } }, cardNumber: "039" },
  { id: 50, name: "Virus", cost: 1, type: "event", tags: ["microbe"], expansion: "base", effects: { description: "Remove up to 2 animals or 5 plants from any player." }, cardNumber: "050" },
  { id: 62, name: "Mineral Deposit", cost: 5, type: "event", tags: [], expansion: "base", effects: { resources: { steel: 5 } }, cardNumber: "062" },
  { id: 63, name: "Mining Expedition", cost: 12, type: "event", tags: [], expansion: "base", effects: { oxygenSteps: 1, resources: { steel: 2 } }, cardNumber: "063" },
  { id: 66, name: "Land Claim", cost: 1, type: "event", tags: [], expansion: "base", effects: { description: "Place marker on non-reserved area. Only you may place there." }, cardNumber: "066" },
  { id: 75, name: "Towing A Comet", cost: 23, type: "event", tags: ["space"], expansion: "base", effects: { oceanTiles: 1, oxygenSteps: 1, resources: { plants: 2 } }, cardNumber: "075" },
  { id: 78, name: "Ice Cap Melting", cost: 5, type: "event", tags: [], expansion: "base", requirements: { minTemperature: 2 }, effects: { oceanTiles: 1 }, cardNumber: "078" },
  { id: 91, name: "Sabotage", cost: 1, type: "event", tags: [], expansion: "base", effects: { description: "Remove 3 titanium, 4 steel, or reduce MC prod 2 from any player." }, cardNumber: "091" },
  { id: 94, name: "Hired Raiders", cost: 1, type: "event", tags: [], expansion: "base", effects: { description: "Steal up to 2 steel or 3MC from any player." }, cardNumber: "094" },
  { id: 100, name: "Large Convoy", cost: 36, type: "event", tags: ["space", "earth"], expansion: "base", effects: { oceanTiles: 1, resources: { plants: 5 }, drawCards: 2, vp: 2 }, cardNumber: "143" },
  { id: 104, name: "Lava Flows", cost: 18, type: "event", tags: [], expansion: "base", effects: { temperatureSteps: 2 }, cardNumber: "140" },
  { id: 113, name: "Business Contacts", cost: 7, type: "event", tags: ["earth"], expansion: "base", effects: { drawCards: 4, description: "Look at top 4, keep 2." }, cardNumber: "111" },
  { id: 114, name: "Bribed Committee", cost: 7, type: "event", tags: ["earth"], expansion: "base", effects: { tr: 2 }, cardNumber: "112" },
  { id: 115, name: "Solar Probe", cost: 9, type: "event", tags: ["space", "science"], expansion: "base", effects: { drawCards: 1, description: "Draw 1 per 3 science tags." }, cardNumber: "181" },
  { id: 126, name: "Convoy From Europa", cost: 15, type: "event", tags: ["space"], expansion: "base", effects: { oceanTiles: 1, drawCards: 1 }, cardNumber: "161" },
  { id: 127, name: "Imported GHG", cost: 7, type: "event", tags: ["space", "earth"], expansion: "base", effects: { production: { heat: 1 }, resources: { heat: 3 } }, cardNumber: "162" },
  { id: 128, name: "Imported Nitrogen", cost: 23, type: "event", tags: ["space", "earth"], expansion: "base", effects: { tr: 1, resources: { plants: 4 }, description: "Add 3 microbes and 2 animals." }, cardNumber: "163" },
  { id: 132, name: "Import of Advanced GHG", cost: 9, type: "event", tags: ["space", "earth"], expansion: "base", effects: { production: { heat: 2 } }, cardNumber: "167" },
  { id: 150, name: "CEO's Favorite Project", cost: 1, type: "event", tags: [], expansion: "base", effects: { description: "Add 1 resource to any card with resources." }, cardNumber: "149" },
  { id: 152, name: "Investment Loan", cost: 3, type: "event", tags: ["earth"], expansion: "base", effects: { production: { megacredits: -1 }, resources: { megacredits: 10 } }, cardNumber: "151" },
  { id: 183, name: "Ice Asteroid", cost: 23, type: "event", tags: ["space"], expansion: "base", effects: { oceanTiles: 2 }, cardNumber: "078a" },
  { id: 185, name: "Giant Ice Asteroid", cost: 36, type: "event", tags: ["space"], expansion: "base", effects: { temperatureSteps: 2, oceanTiles: 2 }, cardNumber: "080a" },
  { id: 190, name: "Technology Demonstration", cost: 5, type: "event", tags: ["science", "space"], expansion: "base", effects: { drawCards: 2 }, cardNumber: "204" },
  { id: 192, name: "Special Design", cost: 4, type: "event", tags: ["science"], expansion: "base", effects: { description: "Next card: global requirements +/- 2." }, cardNumber: "206" },
  { id: 202, name: "Subterranean Reservoir", cost: 11, type: "event", tags: [], expansion: "base", effects: { oceanTiles: 1 }, cardNumber: "127" },
  { id: 203, name: "Permafrost Extraction", cost: 8, type: "event", tags: [], expansion: "base", requirements: { minTemperature: -8 }, effects: { oceanTiles: 1 }, cardNumber: "191" },
  { id: 204, name: "Invention Contest", cost: 2, type: "event", tags: ["science"], expansion: "base", effects: { drawCards: 3, description: "Look at top 3, take 1." }, cardNumber: "192" },
  { id: 205, name: "Martian Survey", cost: 9, type: "event", tags: ["science"], expansion: "base", requirements: { maxOxygen: 4 }, effects: { drawCards: 2, vp: 1 }, cardNumber: "193" },
  { id: 207, name: "Supply Drop", cost: 4, type: "event", tags: [], expansion: "base", effects: { resources: { titanium: 3, steel: 8, plants: 3 } }, cardNumber: "196" },
  { id: 64, name: "Mining Area", cost: 4, type: "automated", tags: ["building"], expansion: "base", effects: { description: "Place on steel/titanium bonus area. +1 that production." }, cardNumber: "064" },
  { id: 67, name: "Mining Rights", cost: 9, type: "automated", tags: ["building"], expansion: "base", effects: { description: "Place on steel/titanium bonus area. +1 that production." }, cardNumber: "067" },
  { id: 119, name: "Greenhouses", cost: 6, type: "automated", tags: ["plant", "building"], expansion: "base", effects: { description: "Gain 1 plant per city tile in play." }, cardNumber: "096" },
  { id: 77, name: "Solar Wind Power", cost: 11, type: "automated", tags: ["space", "power", "science"], expansion: "base", effects: { production: { energy: 1 }, resources: { titanium: 2 } }, cardNumber: "077" },
  { id: 79, name: "Terraforming Ganymede", cost: 33, type: "automated", tags: ["space", "jovian"], expansion: "base", effects: { tr: 1, vp: 2, description: "+1 TR per jovian tag." }, cardNumber: "079" },

  // ========================================
  // PRELUDE CARDS (35 cards - cost 0, free to play)
  // ========================================
  { id: 301, name: "Allied Bank", cost: 0, type: "prelude", tags: ["earth"], expansion: "prelude", effects: { production: { megacredits: 4 }, resources: { megacredits: 3 } }, cardNumber: "P01" },
  { id: 302, name: "Aquifer Turbines", cost: 0, type: "prelude", tags: [], expansion: "prelude", effects: { production: { energy: 2 }, oceanTiles: 1, description: "Pay 3MC." }, cardNumber: "P02" },
  { id: 303, name: "Biofuels", cost: 0, type: "prelude", tags: ["microbe"], expansion: "prelude", effects: { production: { energy: 1, plants: 1 }, resources: { plants: 2 } }, cardNumber: "P03" },
  { id: 304, name: "Biolab", cost: 0, type: "prelude", tags: ["science"], expansion: "prelude", effects: { production: { plants: 1 }, drawCards: 3 }, cardNumber: "P04" },
  { id: 305, name: "Biosphere Support", cost: 0, type: "prelude", tags: ["plant"], expansion: "prelude", effects: { production: { megacredits: -1, plants: 2 } }, cardNumber: "P05" },
  { id: 306, name: "Business Empire", cost: 0, type: "prelude", tags: ["earth"], expansion: "prelude", effects: { production: { megacredits: 6 }, description: "Pay 6MC." }, cardNumber: "P06" },
  { id: 307, name: "Dome Farming", cost: 0, type: "prelude", tags: ["plant", "building"], expansion: "prelude", effects: { production: { megacredits: 2, plants: 1 } }, cardNumber: "P07" },
  { id: 308, name: "Donation", cost: 0, type: "prelude", tags: [], expansion: "prelude", effects: { resources: { megacredits: 21 } }, cardNumber: "P08" },
  { id: 309, name: "Early Settlement", cost: 0, type: "prelude", tags: ["city", "building"], expansion: "prelude", effects: { production: { plants: 1 }, cityTiles: 1 }, cardNumber: "P09" },
  { id: 310, name: "Ecology Experts", cost: 0, type: "prelude", tags: ["plant", "microbe"], expansion: "prelude", effects: { production: { plants: 1 }, description: "Play a card ignoring global requirements." }, cardNumber: "P10" },
  { id: 311, name: "Excentric Sponsor", cost: 0, type: "prelude", tags: [], expansion: "prelude", effects: { description: "Play a card from hand, reducing cost by 25MC." }, cardNumber: "P11" },
  { id: 312, name: "Experimental Forest", cost: 0, type: "prelude", tags: ["plant"], expansion: "prelude", effects: { greeneryTiles: 1, description: "Draw 2 plant tag cards." }, cardNumber: "P12" },
  { id: 313, name: "Galilean Mining", cost: 0, type: "prelude", tags: ["jovian"], expansion: "prelude", effects: { production: { titanium: 2 }, description: "Pay 5MC." }, cardNumber: "P13" },
  { id: 314, name: "Great Aquifer", cost: 0, type: "prelude", tags: [], expansion: "prelude", effects: { oceanTiles: 2 }, cardNumber: "P14" },
  { id: 315, name: "Huge Asteroid", cost: 0, type: "prelude", tags: [], expansion: "prelude", effects: { temperatureSteps: 3, resources: { megacredits: 5 } }, cardNumber: "P15" },
  { id: 316, name: "Io Research Outpost", cost: 0, type: "prelude", tags: ["science", "jovian"], expansion: "prelude", effects: { production: { titanium: 1 }, drawCards: 1 }, cardNumber: "P16" },
  { id: 317, name: "Loan", cost: 0, type: "prelude", tags: [], expansion: "prelude", effects: { production: { megacredits: -2 }, resources: { megacredits: 30 } }, cardNumber: "P17" },
  { id: 318, name: "Martian Industries", cost: 0, type: "prelude", tags: ["building"], expansion: "prelude", effects: { production: { energy: 1, steel: 1 }, resources: { megacredits: 6 } }, cardNumber: "P18" },
  { id: 319, name: "Metal-Rich Asteroid", cost: 0, type: "prelude", tags: [], expansion: "prelude", effects: { temperatureSteps: 1, resources: { titanium: 4, steel: 4 } }, cardNumber: "P19" },
  { id: 320, name: "Metals Company", cost: 0, type: "prelude", tags: [], expansion: "prelude", effects: { production: { megacredits: 1, steel: 1, titanium: 1 } }, cardNumber: "P20" },
  { id: 321, name: "Mining Operations", cost: 0, type: "prelude", tags: ["building"], expansion: "prelude", effects: { production: { steel: 2 }, resources: { steel: 4 } }, cardNumber: "P21" },
  { id: 322, name: "Mohole", cost: 0, type: "prelude", tags: ["building"], expansion: "prelude", effects: { production: { heat: 3 }, resources: { heat: 3 } }, cardNumber: "P22" },
  { id: 323, name: "Mohole Excavation", cost: 0, type: "prelude", tags: ["building"], expansion: "prelude", effects: { production: { steel: 1, heat: 2 }, resources: { heat: 2 } }, cardNumber: "P23" },
  { id: 324, name: "Nitrogen Shipment", cost: 0, type: "prelude", tags: [], expansion: "prelude", effects: { tr: 1, resources: { megacredits: 5 }, production: { plants: 1 } }, cardNumber: "P24" },
  { id: 325, name: "Orbital Construction Yard", cost: 0, type: "prelude", tags: ["space"], expansion: "prelude", effects: { production: { titanium: 1 }, resources: { titanium: 4 } }, cardNumber: "P25" },
  { id: 326, name: "Point Luna", cost: 0, type: "prelude", tags: ["earth", "space"], expansion: "prelude", effects: { production: { titanium: 1 }, drawCards: 1 }, cardNumber: "P26" },
  { id: 327, name: "Polar Industries", cost: 0, type: "prelude", tags: ["building"], expansion: "prelude", effects: { production: { heat: 2 }, oceanTiles: 1 }, cardNumber: "P27" },
  { id: 328, name: "Power Generation", cost: 0, type: "prelude", tags: ["power"], expansion: "prelude", effects: { production: { energy: 3 } }, cardNumber: "P28" },
  { id: 329, name: "Research Network", cost: 0, type: "prelude", tags: ["wild"], expansion: "prelude", effects: { drawCards: 3, description: "Wild tag counts as any tag." }, cardNumber: "P29" },
  { id: 330, name: "Self-Sufficient Settlement", cost: 0, type: "prelude", tags: ["city", "building"], expansion: "prelude", effects: { production: { megacredits: 2 }, cityTiles: 1 }, cardNumber: "P30" },
  { id: 331, name: "Smelting Plant", cost: 0, type: "prelude", tags: ["building"], expansion: "prelude", effects: { oxygenSteps: 2, resources: { steel: 5 } }, cardNumber: "P31" },
  { id: 332, name: "Society Support", cost: 0, type: "prelude", tags: [], expansion: "prelude", effects: { production: { megacredits: -1, plants: 1, energy: 1, heat: 1 } }, cardNumber: "P32" },
  { id: 333, name: "Supplier", cost: 0, type: "prelude", tags: ["power"], expansion: "prelude", effects: { production: { energy: 2 }, resources: { steel: 4 } }, cardNumber: "P33" },
  { id: 334, name: "Supply Drop", cost: 0, type: "prelude", tags: [], expansion: "prelude", effects: { resources: { titanium: 3, steel: 8, plants: 3 } }, cardNumber: "P34" },
  { id: 335, name: "UNMI Contractor", cost: 0, type: "prelude", tags: ["earth"], expansion: "prelude", effects: { tr: 3, drawCards: 1 }, cardNumber: "P35" },

  // ========================================
  // COLONIES PROJECT CARDS (49 cards)
  // ========================================
  { id: 401, name: "Community Services", cost: 13, type: "automated", tags: [], expansion: "colonies", effects: { production: { megacredits: 1 }, vp: 1, description: "+1MC prod per card with no tags." }, cardNumber: "C01" },
  { id: 402, name: "Conscription", cost: 2, type: "event", tags: ["earth"], expansion: "colonies", effects: { vp: -1, description: "Next card costs 16MC less." }, cardNumber: "C02" },
  { id: 403, name: "Corona Extractor", cost: 10, type: "automated", tags: ["space", "power"], expansion: "colonies", requirements: { tag: { tag: "science", count: 4 } }, effects: { production: { energy: 4 } }, cardNumber: "C03" },
  { id: 404, name: "Cryo-Sleep", cost: 10, type: "automated", tags: ["science"], expansion: "colonies", effects: { vp: 1, description: "When trading, you pay 1 less." }, cardNumber: "C04" },
  { id: 405, name: "Earth Elevator", cost: 43, type: "automated", tags: ["space", "earth"], expansion: "colonies", effects: { production: { titanium: 3 }, vp: 4 }, cardNumber: "C05" },
  { id: 406, name: "Ecology Research", cost: 21, type: "automated", tags: ["science", "plant", "animal", "microbe"], expansion: "colonies", effects: { production: { plants: 1 }, vp: 1, description: "+1 plant prod per colony you have." }, cardNumber: "C06" },
  { id: 407, name: "Floater Leasing", cost: 3, type: "automated", tags: [], expansion: "colonies", effects: { description: "Add 2 floaters to any card." }, cardNumber: "C07" },
  { id: 408, name: "Floater Prototypes", cost: 2, type: "event", tags: ["science"], expansion: "colonies", effects: { description: "Add 2 floaters to any card." }, cardNumber: "C08" },
  { id: 409, name: "Floater Technology", cost: 7, type: "active", tags: ["science"], expansion: "colonies", effects: { description: "Action: Add 1 floater to any card." }, cardNumber: "C09" },
  { id: 410, name: "Galilean Waystation", cost: 15, type: "automated", tags: ["space"], expansion: "colonies", effects: { vp: 1, description: "+1MC prod per jovian tag." }, cardNumber: "C10" },
  { id: 411, name: "Heavy Taxation", cost: 3, type: "automated", tags: ["earth"], expansion: "colonies", effects: { production: { megacredits: 2 }, vp: -1 }, cardNumber: "C11" },
  { id: 412, name: "Ice Moon Colony", cost: 23, type: "automated", tags: ["space"], expansion: "colonies", effects: { oceanTiles: 1, description: "Place a colony." }, cardNumber: "C12" },
  { id: 413, name: "Impactor Swarm", cost: 11, type: "event", tags: ["space"], expansion: "colonies", effects: { resources: { heat: 12 } }, cardNumber: "C13" },
  { id: 414, name: "Interplanetary Colony Ship", cost: 12, type: "event", tags: ["space", "earth"], expansion: "colonies", effects: { description: "Place a colony." }, cardNumber: "C14" },
  { id: 415, name: "Jovian Lanterns", cost: 20, type: "automated", tags: ["jovian"], expansion: "colonies", effects: { tr: 1, description: "Add 2 floaters here. 1VP per 2 floaters." }, cardNumber: "C15" },
  { id: 416, name: "Jupiter Floating Station", cost: 9, type: "active", tags: ["jovian"], expansion: "colonies", effects: { vp: 1, description: "Action: Add 1 floater here. +1MC prod per jovian tag." }, cardNumber: "C16" },
  { id: 417, name: "Lunar Exports", cost: 19, type: "automated", tags: ["space", "earth"], expansion: "colonies", effects: { production: { plants: 2 }, description: "OR: +5MC prod instead." }, cardNumber: "C17" },
  { id: 418, name: "Lunar Mining", cost: 11, type: "automated", tags: ["earth"], expansion: "colonies", effects: { production: { titanium: 2 } }, cardNumber: "C18" },
  { id: 419, name: "Market Manipulation", cost: 1, type: "event", tags: ["earth"], expansion: "colonies", effects: { description: "Increase/decrease a colony tile track." }, cardNumber: "C19" },
  { id: 420, name: "Martian Zoo", cost: 12, type: "active", tags: ["animal", "building"], expansion: "colonies", effects: { vp: 1, description: "Effect: When you play an earth tag, add 1 animal here. Action: Gain 1MC per animal here." }, cardNumber: "C20" },
  { id: 421, name: "Minority Refuge", cost: 5, type: "automated", tags: ["space"], expansion: "colonies", effects: { production: { megacredits: 2 }, description: "Place a colony." }, cardNumber: "C21" },
  { id: 422, name: "Molecular Printing", cost: 11, type: "automated", tags: ["science"], expansion: "colonies", effects: { description: "Gain 1MC per city. Gain 1MC per colony." }, cardNumber: "C22" },
  { id: 423, name: "National Park", cost: 12, type: "automated", tags: ["plant", "building"], expansion: "colonies", requirements: { minTemperature: -14 }, effects: { production: { megacredits: 2 }, resources: { plants: 2 }, greeneryTiles: 1 }, cardNumber: "C23" },
  { id: 424, name: "Pioneer Settlement", cost: 13, type: "automated", tags: ["space"], expansion: "colonies", effects: { production: { megacredits: -2 }, vp: 2, description: "Place a colony." }, cardNumber: "C24" },
  { id: 425, name: "Productive Outpost", cost: 0, type: "automated", tags: [], expansion: "colonies", effects: { description: "Gain all colony bonuses." }, cardNumber: "C25" },
  { id: 426, name: "Quantum Communications", cost: 8, type: "automated", tags: [], expansion: "colonies", requirements: { tag: { tag: "science", count: 4 } }, effects: { production: { megacredits: 1 }, description: "+1MC prod per colony in play." }, cardNumber: "C26" },
  { id: 427, name: "Red Spot Observatory", cost: 25, type: "active", tags: ["science", "jovian"], expansion: "colonies", effects: { drawCards: 2, vp: 2, description: "Action: Add 1 floater here. OR spend 1 floater to draw a card." }, cardNumber: "C27" },
  { id: 428, name: "Refugee Camp", cost: 10, type: "active", tags: [], expansion: "colonies", effects: { production: { megacredits: -1 }, description: "Action: Add 1 camp here. 1VP per camp." }, cardNumber: "C28" },
  { id: 429, name: "Research Colony", cost: 20, type: "automated", tags: ["science", "space"], expansion: "colonies", effects: { drawCards: 2, description: "Place a colony." }, cardNumber: "C29" },
  { id: 430, name: "Rim Freighters", cost: 10, type: "automated", tags: ["space"], expansion: "colonies", effects: { description: "When trading, you pay 1 less." }, cardNumber: "C30" },
  { id: 431, name: "Sky Docks", cost: 18, type: "automated", tags: ["space", "earth"], expansion: "colonies", effects: { cardDiscount: 1, vp: 2, description: "Place a colony." }, cardNumber: "C31" },
  { id: 432, name: "Solar Reflectors", cost: 23, type: "automated", tags: ["space"], expansion: "colonies", effects: { production: { heat: 5 } }, cardNumber: "C32" },
  { id: 433, name: "Space Port", cost: 22, type: "automated", tags: ["city", "building"], expansion: "colonies", effects: { production: { megacredits: 4 }, cityTiles: 1, description: "Place colony. -1 energy prod." }, cardNumber: "C33" },
  { id: 434, name: "Space Port Colony", cost: 27, type: "automated", tags: ["space"], expansion: "colonies", effects: { vp: 3, description: "Place a colony. Gain TR per colony on that tile." }, cardNumber: "C34" },
  { id: 435, name: "Spin-Off Department", cost: 10, type: "automated", tags: [], expansion: "colonies", effects: { production: { megacredits: 2 }, description: "Draw a card per space tag." }, cardNumber: "C35" },
  { id: 436, name: "Sub-Zero Salt Fish", cost: 5, type: "active", tags: ["animal"], expansion: "colonies", requirements: { minTemperature: -6 }, effects: { production: { plants: -1 }, vpPerResource: { resource: "animal", per: 2 }, description: "Action: Add 1 animal here." }, cardNumber: "C36" },
  { id: 437, name: "Titan Air Scrapping", cost: 21, type: "active", tags: ["jovian"], expansion: "colonies", effects: { vp: 2, description: "Action: Spend 1 titanium to add 2 floaters here. 1VP per 2 floaters." }, cardNumber: "C37" },
  { id: 438, name: "Titan Floating Launch-Pad", cost: 18, type: "active", tags: ["jovian"], expansion: "colonies", effects: { vp: 1, description: "Action: Spend 1 floater here to place a colony. Add 1 floater here." }, cardNumber: "C38" },
  { id: 439, name: "Titan Shuttles", cost: 23, type: "active", tags: ["space", "jovian"], expansion: "colonies", effects: { vp: 1, description: "Action: Add 2 floaters here, or spend 1 floater to add 1 titanium." }, cardNumber: "C39" },
  { id: 440, name: "Trade Envoys", cost: 6, type: "automated", tags: [], expansion: "colonies", effects: { description: "When trading, you may first increase that colony track 1 step." }, cardNumber: "C40" },
  { id: 441, name: "Trading Colony", cost: 18, type: "automated", tags: ["space"], expansion: "colonies", effects: { description: "Place a colony. When trading, gain 2 extra resources." }, cardNumber: "C41" },
  { id: 442, name: "Troposphere Harvesting", cost: 12, type: "automated", tags: [], expansion: "colonies", effects: { production: { megacredits: 2 }, vp: 1, description: "+1MC per floater you have." }, cardNumber: "C42" },
  { id: 443, name: "Urban Decomposers", cost: 6, type: "active", tags: ["microbe"], expansion: "colonies", effects: { description: "Action: Add 1 microbe here. Effect: When placing a city, add 1 microbe. 1VP per 3 microbes.", vpPerResource: { resource: "microbe", per: 3 } }, cardNumber: "C43" },
  { id: 444, name: "Air Raid", cost: 0, type: "event", tags: [], expansion: "colonies", effects: { description: "Steal 5MC from any player by spending 1 floater." }, cardNumber: "C44" },
  { id: 445, name: "Atmo Collectors", cost: 15, type: "active", tags: [], expansion: "colonies", effects: { description: "Add 3 floaters. Action: Spend 1 floater to gain 2 of any standard resource." }, cardNumber: "C45" },
  { id: 446, name: "Lander Technology", cost: 8, type: "active", tags: ["science"], expansion: "colonies", effects: { description: "Effect: When you play a space event, gain 2MC." }, cardNumber: "C46" },
  { id: 447, name: "Arboreal Biodiversity", cost: 17, type: "automated", tags: ["plant", "animal"], expansion: "colonies", effects: { production: { plants: 2 }, greeneryTiles: 1, description: "Add 2 animals to any card." }, cardNumber: "C47" },
  { id: 448, name: "Eco Line", cost: 14, type: "automated", tags: ["plant"], expansion: "colonies", effects: { production: { plants: 2 }, resources: { plants: 3 } }, cardNumber: "C48" },
  { id: 449, name: "Poseidon", cost: 12, type: "automated", tags: ["space"], expansion: "colonies", effects: { production: { megacredits: 1 }, description: "+1MC prod per colony." }, cardNumber: "C49" },
];
